title: all about whales
author: christina
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 whales are very huge creatures. they are the biggest creatures in the world. specifically the blue whale

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  cnaje1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
